name: node-template
version: 0.5.0
description: A Typescript/node.js project template
license: Unlicense
engines:
  node: ^22.18
  pnpm: ^10.15
type: module
bin:
  hello: bin/src/hello.js
scripts:
  build: tsc --build
  clean: rm -rf bin
  lint: eslint
  lint-fix: eslint --fix
  pretty: prettier . --check
  pretty-fix: prettier . --write
  pretest: tsc --build
  test: NODE_OPTIONS=--enable-source-maps jasmine
  hello: tsx src/hello.ts
devDependencies:
  '@eslint/js': ^9.17.0
  '@ianvs/prettier-plugin-sort-imports': ^4.7.0
  '@types/eslint-config-prettier': 6.11.3
  '@types/jasmine': ^5.1.9
  '@types/node': ^24.3.0
  eslint: ^9.34.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-jasmine: ^4.2.2
  eslint-plugin-tsdoc: ^0.4.0
  globals: ^16.3.0
  jasmine: ^5.10.0
  prettier: ^3.6.2
  tsx: ^4.20.5
  typescript: ^5.9.2
  typescript-eslint: ^8.42.0
dependencies:
  chalk: ^5.6.0
prettier:
  semi: false
  singleQuote: true
  trailingComma: all
  bracketSpacing: false
  printWidth: 100
  plugins:
    - '@ianvs/prettier-plugin-sort-imports'
  importOrder:
    - <BUILTIN_MODULES>
    - <THIRD_PARTY_MODULES>
    - ^[.]
  importOrderParserPlugins:
    - typescript
  importOrderTypeScriptVersion: 5.7.2
  importOrderCaseSensitive: false
